services:
  mongo-0:
    image: bitnami/mongodb:7.0.15
    restart: unless-stopped
    environment:
      MONGODB_ADVERTISED_HOSTNAME: mongo-0
      MONGODB_ROOT_PASSWORD: mongo123
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: replicasetkey123
      MONGODB_EXTRA_FLAGS: --oplogSize=256
      MONGODB_DATABASE: coursework
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - 'mongodb_master_data:/bitnami'
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ulimits:
      nofile:
        soft: 100000
        hard: 100000
    networks:
      - net
  mongo:
    image: bitnami/mongodb:7.0.15
    depends_on:
      - mongo-0
    restart: unless-stopped
    environment:
      MONGODB_INITIAL_PRIMARY_HOST: mongo-0
      MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD: mongo123
      MONGODB_REPLICA_SET_MODE: secondary
      MONGODB_REPLICA_SET_KEY: replicasetkey123
      MONGODB_EXTRA_FLAGS: --oplogSize=256
      MONGODB_DATABASE: coursework
    ports:
      - "127.0.0.1:27018-27019:27017"
    networks:
      - net
networks:
  net:

volumes:
  mongodb_master_data:
    driver: local