eureka.client.enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka

management:
  tracing:
    enabled: true
  zipkin:
    tracing:
      endpoint: http://tempo:9411/api/v2/spans
